# Cnfiguration file that:
#  - Enables security updates
#  - Disables version-updates

version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
