# name: Cypress Firefox

# on: [push]

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     container:
#       # See images at https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
#       image: cypress/browsers:latest
#       options: --user 1001
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version-file: '.nvmrc'

#       - name: Cypress install
#         uses: cypress-io/github-action@v5
#         with:
#           runTests: false
#       # report machine parameters
#       - run: yarn cypress info
#       - run: node --version
#       - run: node -p 'os.cpus()'
#       - run: yarn cy:test:firefox
